### ISSUE TITLE
go-mkopensource: generating dependency file fails with dirty go.mod

### ISSUE THREAD

**Issue by LanceEa** [datawire/go-mkopensource#60]
A typical workflow for many Go projects is to update the `go.mod` run `go mod tidy` and then run the `go-mkopensource` binary to generate a new DEPENDENCY.md. 

However, this currently fails due to not liking the fact that the go.mod file is now "dirty" from a git perspective. The checking for go.mod dirty is good for CI and automation but not for the workflow described above. 

>It may be a little dogmatic but the commits for the updated dependency and the changes to go.mod belong together as an atomic commit.

My current workaround is the following:
- commit `go.mod`
- run `go-mkopensource`
- commit new `DEPENDENCY.md`
- rebase and squash commits together

# Proposal 

add flag that allows us to ignore dirty go.mod and generate anyways. Something like `--ignoreGitDirty` or something like that so that it will generate the file without failing then in CI it will block it because something isn't correct.

**Comment by AliceProxy** [comment]
Conveniently you don't run into this problem if you forget to urn `go-mkopensource` until after CI has failed your first commit for missing the changes it would have made :sunglasses:

**Comment by LanceEa** [comment]
haha yes that is true :)
